[package]
name = "simple-web-server"
version = "0.0.2"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.4.5"
lazy_static = "1.4.0"
hyper = { version = "0.14.5", features = ["full"] }
tokio = { version = "1.4.0", features = ["full"] }
