[package]
name = "simple-web-server"
version = "0.0.2"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.4.2"
lazy_static = "1.4.0"
hyper = "0.13.9"
tokio = { version = "0.2.24", features = ["full"] }
