[package]
name = "warp-test"
version = "0.2.0"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]
edition = "2021"

[dependencies]
getopts = "0.2.21"
tokio = { version = "1.25.0", features = ["full"] }
warp = "0.3.3"
