[package]
name = "warp"
version = "0.1.0"
authors = ["Alexander Slesarev <alex.slesarev@gmail.com>"]
edition = "2018"

[dependencies]
getopts = "0.2.21"
tokio = { version = "1.12.0", features = ["full"] }
warp = "0.3.1"
